### ISSUE TITLE
Список категорий при добавлении категории

### ISSUE THREAD

**Issue by alexey-murashov** [you-all-die/internship#108]
Переделать шаблон, убрать создание категории "Без категории"

**Comment by you-all-die** [comment]
какой шаблон и почему нужно убрать Без категории?

**Comment by alexey-murashov** [comment]
> какой шаблон и почему нужно убрать Без категории?

main/resources/templates/categories/category.html
main/java/com/example/adminapplication/controller/categories/CategoriesController.java - убрать создание новой категории и добавление ее в список, это можно сделать за счет шаблона
