### ISSUE TITLE
Каталог товаров и страница продукта

### ISSUE THREAD

**Issue by you-all-die** [you-all-die/internship#175]
В каталоге товаров, при нажатии на иконку пользователя, отсутствует ссылка на профиль пользователя
На странице товара ссылка на профиль есть, но содержит айдишник профиля, в итоге не работает т.к. маппинг убрали

Есть 2 шаблона fomain и main для хэдера - нужно привести к одному виду, fomain  используется только в каталоге и на странице товара

**Comment by samyual** [comment]
Исправлено
