### ISSUE TITLE
Админка: отдельное приложение

### ISSUE THREAD

**Issue by you-all-die** [you-all-die/internship#72]
В проекте создать папку admin-application
Скопировать в неё весь проект
Удалить все что не относится к админке
Запускаться должна на другом порту (8081 например)
Пока без авторизации

В итоге добиться работоспособности админки как отдельного приложения

Подумать над возможностью вынести сущности в отдельный модуль, что бы можно было подключать как зависимость мавена и на сайте и в админке

**Comment by samyual** [comment]
А может, сразу отдельным модулем как-то его оформлять? Можно ведь, создать проект, который содержит внутри подпроекты, я просто не силён в этом?

**Comment by you-all-die** [comment]
В рамках одного приложения да, можно разделять его на какие то модули, те же сущности вынести в отдельный модуль, или например интеграцию с каким то внешним сервисом тоже можно оформить отдельным модулем в проекте, и подключать его как зависимость в других модулях.

Но в данном случае админка это отдельное приложение, и как модуль сайта все таки не устроит
