### ISSUE TITLE
Site API: Order

### ISSUE THREAD

**Issue by you-all-die** [you-all-die/internship#84]
Методы
	- GET /api/user/{id}/orders - список заказов пользователя, постраничный поиск, размер страницы по умолчанию 5 заказов
	- GET /api/user/{id}/order/{orderId} - информация по заказу
	- POST /api/user/{id}/order - оформление заказа, в теле запроса должны передаваться все необходимые параметра для оформления

**Comment by samyual** [comment]
Вопрос: orderId у нас уникальный, почему тогда запрос /user/{id}/order/{orderId}, объясните, пожалуйста

**Comment by samyual** [comment]
Может, проще информацию по заказу получить по /api/order/{id} ?

**Comment by you-all-die** [comment]
да, получение можно заменить на /api/order/{id}
